stages:
  - build
  - deploy

build:
  stage: build
  script: ./gradlew clean assembleDevRelease assembleProdRelease
  artifacts:
    paths:
      - app/build/outputs
  tags:
    - ANDROID

deploy_staging:
  stage: deploy
  when: manual
  variables:
    APP_SERVER_URL: "http://netptt.cn:20002"
    BUILD_NUMBER: ${CI_PIPELINE_ID}
  environment:
      name: staging
      url: http://netptt.cn:20000
  script:
    - ./gradlew clean assembleDevRelease
    - scp app/build/outputs/apk/app-dev-release.apk root@netptt.cn:/serverDisk/apks/test/xianzhitong-test-${CI_PIPELINE_ID}.apk
    - >
        curl -X POST
        -H "Content-Type: application/json"
        -u admin:123654
        -d "{\"latest_version_code\":${CI_PIPELINE_ID},\"latest_version_name\":\"1.6.${CI_PIPELINE_ID}\",\"update_message\":\"新版本发布\",\"mandatory\":false,\"signal_server_endpoint\":\"https://netptt.cn:20007\",\"signal_server_endpoint_insecure\":\"http://netptt.cn:20000\",\"download_url\":\"http://netptt.cn:8080/test/xianzhitong-test-${CI_PIPELINE_ID}.apk\"}"
        http://netptt.cn:20002/admin
  tags:
    - ANDROID
    - NETPTT_ACCESS
  artifacts:
      paths:
        - app/build/outputs

deploy_production:
  stage: deploy
  when: manual
  variables:
    APP_SERVER_URL: "http://netptt.cn:20002"
  environment:
      name: production
      url: http://netptt.cn:20000
  script:
    - echo "Uploading to netptt..."
    - ./gradlew clean assembleProdRelease
    - scp app/build/outputs/apk/app-prod-release.apk root@netptt.cn:/serverDisk/apks/prod/xianzhitong-1.5.apk
  tags:
    - ANDROID
    - NETPTT_ACCESS
  artifacts:
      paths:
        - app/build/outputs