stages:
  - build
  - deploy

build:
  stage: build
  script: ./gradlew clean assembleDevRelease assembleProdRelease
  artifacts:
    paths:
      - app/build/outputs
  tags:
    - ANDROID

deploy_staging:
  stage: deploy
  when: manual
  variables:
    APP_SERVER_URL: "http://netptt.cn:20002"
    BUILD_NUMBER: ${CI_PIPELINE_ID}
  environment:
      name: staging
      url: http://netptt.cn:20000
  script:
    - ./gradlew clean assembleDevRelease
    - scp app/build/outputs/apk/app-dev-release.apk root@netptt.cn:/serverDisk/apks/test/xianzhitong-test-${CI_PIPELINE_ID}.apk
  tags:
    - ANDROID
    - NETPTT_ACCESS
  artifacts:
      paths:
        - app/build/outputs

deploy_production:
  stage: deploy
  when: manual
  variables:
    APP_SERVER_URL: "http://netptt.cn:20002"
  environment:
      name: production
      url: http://netptt.cn:20000
  script:
    - echo "Uploading to netptt..."
    - ./gradlew clean assembleProdRelease
    - scp app/build/outputs/apk/app-prod-release.apk root@netptt.cn:/serverDisk/apks/prod/xianzhitong-1.5.apk
  tags:
    - ANDROID
    - NETPTT_ACCESS
  artifacts:
      paths:
        - app/build/outputs