stages:
  - build
  - deploy

build:
  image: runmymind/docker-android-sdk
  stage: build
  variables:
      APP_SERVER_URL: "http://netptt.cn:25002"
      BUILD_NUMBER: ${CI_PIPELINE_ID}
  script: ./gradlew --no-daemon clean :app:assembleDevRelease :console-app:assembleDevDebug
  artifacts:
    paths:
      - app/build/outputs
      - console-app/build/outputs

deploy_app_staging:
  image: ubuntu:16.04
  stage: deploy
  when: manual
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  environment:
      name: staging
      url: http://netptt.cn:25000
  script:
    - export CHANGE_LOG="`./generate_gitlog.sh`"
    - echo $CHANGE_LOG
    - scp app/build/outputs/apk/app-dev-release.apk root@netptt.cn:/serverDisk/apks/zrt_staging/zrt-ptt-staging-${CI_PIPELINE_ID}.apk
    - >
        curl -X POST
        -H "Content-Type: application/json"
        -u admin:123654
        -d "{\"latest_version_code\":${CI_PIPELINE_ID},\"latest_version_name\":\"1.6.${CI_PIPELINE_ID}\",\"update_message\":\"<ul>${CHANGE_LOG}<li>...</li></ul>\",\"mandatory\":false,\"signal_server_endpoint\":\"https://netptt.cn:25007\",\"signal_server_endpoint_insecure\":\"http://netptt.cn:25000\",\"download_url\":\"http://netptt.cn:8080/zrt_staging/zrt-ptt-staging-${CI_PIPELINE_ID}.apk\"}"
        http://netptt.cn:25002/admin

deploy_console_staging:
  image: ubuntu:16.04
  stage: deploy
  when: manual
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  environment:
      name: staging
      url: http://netptt.cn:25000
  script:
    - scp console-app/build/outputs/apk/console-app-dev-debug.apk root@netptt.cn:/serverDisk/apks/zrt_staging/zrt-ptt-console-staging-${CI_PIPELINE_ID}.apk
  artifacts:
      paths:
        - app/build/outputs
