stages:
  - build
  - deploy

build:
  stage: build
  script: ./gradlew --no-daemon clean assembleDevRelease
  artifacts:
    paths:
      - app/build/outputs
  tags:
    - ANDROID

deploy_staging:
  stage: deploy
  when: manual
  variables:
    APP_SERVER_URL: "http://netptt.cn:25002"
    BUILD_NUMBER: ${CI_PIPELINE_ID}
  environment:
      name: staging
      url: http://netptt.cn:25000
  script:
    - export CHANGE_LOG="`./generate_gitlog.sh`"
    - echo $CHANGE_LOG
    - ./gradlew --no-daemon clean assembleDevRelease
    - scp app/build/outputs/apk/app-dev-release.apk root@netptt.cn:/serverDisk/apks/zrt_staging/zrt-ptt-staging-${CI_PIPELINE_ID}.apk
    - >
        curl -X POST
        -H "Content-Type: application/json"
        -u admin:123654
        -d "{\"latest_version_code\":${CI_PIPELINE_ID},\"latest_version_name\":\"1.6.${CI_PIPELINE_ID}\",\"update_message\":\"<ul>${CHANGE_LOG}<li>...</li></ul>\",\"mandatory\":false,\"signal_server_endpoint\":\"https://netptt.cn:25007\",\"signal_server_endpoint_insecure\":\"http://netptt.cn:25000\",\"download_url\":\"http://netptt.cn:8080/zrt_staging/zrt-ptt-staging-${CI_PIPELINE_ID}.apk\"}"
        http://netptt.cn:25002/admin
  tags:
    - ANDROID
    - NETPTT_ACCESS
  artifacts:
      paths:
        - app/build/outputs
